
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package com.rpm.pixelcat.interpreter;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int MINUS = 3;
  public static final int INT = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int MUL = 4;
  public static final int LPAREN = 6;
  public static final int FLOAT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "LPAREN",
  "RPAREN",
  "INT",
  "FLOAT"
  };

  /* non terminals */
  static final int expr = 1;
  static final int expr_list = 0;
  static final int op = 2;
}

